### ISSUE TITLE
ActionSheet 增加 openType选项

### ISSUE THREAD

**Issue by yun77op** [youzan/zanui-weapp#100]
场景是ActionSheet里需要触发转发，而页面内发起转发需要通过给 button 组件设置属性 open-type="share"，但现有action view是text而不是button。

不知各位意见如何？

**Comment by pangxie1991** [comment]
恩，这个我看下。确实支持 open-type 以后，用起来场景更广泛

**Comment by pangxie1991** [comment]
已经增加 open-type 支持，新的版本预计这周五会发

现在只是支持了 open-type，open-type 对应的其他那些属性暂时还没加，感觉用到的几率不高，如果有需要可以再提

**Comment by yun77op** [comment]
Nice

Yao <notifications@github.com> 于 2018年1月9日周二 下午3:12写道：
