### ISSUE TITLE
使用"单元格"时，icon无法使用

### ISSUE THREAD

**Issue by ldbmcs** [youzan/zanui-weapp#101]
VM6063:2 Failed to load font https://b.yzcdn.cn/zanui-weapp/zanui-weapp-icon-4381aded05.woff2
net::ERR_CACHE_MISS 
From server 183.222.230.253

报错如上，请问下应该怎么解决？

**Comment by pangxie1991** [comment]
这个是网络情况导致的，我看了下 https://b.yzcdn.cn/zanui-weapp/zanui-weapp-icon-4381aded05.woff2 这个链接在 17ce 上跑了下，除了部分比较偏远的地区，其他都可以的

另外，假设这个 https://b.yzcdn.cn/zanui-weapp/zanui-weapp-icon-4381aded05.woff2 挂了，应该也不会影响 icon 使用吧，毕竟还有好多其他可选的地址
