### ISSUE TITLE
将现有版本发布最新版小程序

### ISSUE THREAD

**Issue by bestony** [youzan/zanui-weapp#102]
### 问题描述

由于需要在移动端查看最新的组件样式(在开发者工具中切换较为麻烦)，能否发布代码库中的版本到小程序平台上？

举例：目前小程序中的 Panel 和源码中的 Panel 并不相同。

**Comment by pangxie1991** [comment]
发布的小程序会根据最新的 tag 走的，最新 2.4.3 的示例小程序已经在审核中了

**Comment by pangxie1991** [comment]
已经发布
