### ISSUE TITLE
如何同时使用noticebar与tab标签，js中应该如何写。这部分是不一样的

### ISSUE THREAD

**Issue by rhkxa** [youzan/zanui-weapp#105]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
文档里的写了每个组件的使用方式，只要结合在一起使用就好了
```js
const { Noticebar, Tab, extend } = require('path/to/zanui-weapp/dist/index');

Page(extend({}, Noticebar, Tab, {
    handleZanTabChange({ componentId, selectId }) {}
}));
```
