### ISSUE TITLE
field组件外层使用zan-panel会造成input边框不显示

### ISSUE THREAD

**Issue by jllyzzd** [youzan/zanui-weapp#107]
`  <view class="zan-panel">
<view class="zan-cell">
      <template is="zan-field" data="{{ ...config.radius.notitle, componentId: 'test' }}"></template>
    </view>
  </view>`
 
这个tast会不显示input元素的边框。

**Comment by pangxie1991** [comment]
不需要额外套一个 zan-cell, 直接使用 zan-field 模板就好，具体使用可以看 example 下的各个组件示例代码
```html
<view class="zan-panel">
  <template
      is="zan-field"
      data="{{ ...config.base.name, value }}"></template>
  <template
      is="zan-field"
      data="{{ ...config.base.tel }}"></template>
  <template
      is="zan-field"
      data="{{ ...config.base.address }}"></template>
</view>
```
