### ISSUE TITLE
在小程序微信开发工具中会报字体加载错误

### ISSUE THREAD

**Issue by jllyzzd** [youzan/zanui-weapp#108]
VM2807:2 Failed to load font https://b.yzcdn.cn/zanui-weapp/zanui-weapp-icon-4381aded05.woff2
net::ERR_CACHE_MISS 
From server 27.221.30.38

**Comment by pangxie1991** [comment]
#101 和这个是同一个问题，不影响使用的~

**Comment by joe434200** [comment]
@pangxie1991 大哥，这个真的会影响使用，用户第一次用户加载不了，每次我在开发工具中清理缓存后，总会出现第一次加载出错，导致我的页面部分内容无法渲染
