### ISSUE TITLE
文档写的真不走心 各种错误

### ISSUE THREAD

**Issue by liubeibei125** [youzan/zanui-weapp#11]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by chenjiahan** [comment]
此仓库已废弃，请移步 https://github.com/youzan/vant-weapp
