### ISSUE TITLE
 *新增功能* 能否在example的field中增加picker-view的示例？拜托了

### ISSUE THREAD

**Issue by aaronuu** [youzan/zanui-weapp#110]
如题！Thanks！

**Comment by pangxie1991** [comment]
ok，我看下

**Comment by pangxie1991** [comment]
picker-view 不同 picker，是直接把选项展示在页面里。所以这里的示例建议是配合 popup 使用，在 popup 展示 picker-view 的选项，在 Field 内容区展示选中后的选项信息

**Comment by pangxie1991** [comment]
具体可以看 dev 上的 example

**Comment by aaronuu** [comment]
非常感谢，辛苦了
