### ISSUE TITLE
*提交BUG*Setting data field "zanTopTips.timer" to undefined is invalid.

### ISSUE THREAD

**Issue by youngjuning** [youzan/zanui-weapp#113]
其实就是toptips组件的demo，控制台会报错

**Comment by pangxie1991** [comment]
恩，最近微信对设置 undefined 会开始报错，我们在清理了

**Comment by youngjuning** [comment]
@pangxie1991 设置为 false 会不会更加好一点

**Comment by pangxie1991** [comment]
恩，关于 API 的调用方式，这个要再升级下

看了下，应该是设置为 0 比较合理，因为 setTimeout 本来就是返回正整数的

**Comment by youngjuning** [comment]
@pangxie1991 确实0就完美了
