### ISSUE TITLE
请问步骤条控件是否支持vertical属性时自定义两个步骤间那条线的长度？

### ISSUE THREAD

**Issue by lijunyandev** [youzan/zanui-weapp#120]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
这个现在还不支持
