### ISSUE TITLE
购物车里边如何使用计数器组件

### ISSUE THREAD

**Issue by youngjuning** [youzan/zanui-weapp#122]
就是数据是动态生成的，我怎么区分控制每一个steper

**Comment by youngjuning** [comment]
![2018-01-29_133043](https://user-images.githubusercontent.com/13204332/35494869-9fe1f380-04f8-11e8-94f5-f25da8dece05.png)
...后边我写 stepper+index不对

**Comment by youngjuning** [comment]
@pangxie1991 求救啊，看到推荐的小程序里是实现了的

**Comment by pangxie1991** [comment]
只要 componentId 传的不一样，handleZanStepperChange 里就可以接收到不同的 componentId，根据这个可以做 switch case 之类的代码

**Comment by pangxie1991** [comment]
具体可以看下 example/stepper 里的代码

**Comment by hfxu** [comment]
我也有类似的需求，不过我用以下的方法实现了在用wx:for循环动态创建多个`Stepper`。

1. 页面：
`<view wx:for="{{items}}">
    <template is="zan-stepper" data="{{...item.stepper, componentId: index}}">
    </template>
 </view>`

2. JS：
`Page(Object.assign({}, Zan.Stepper, {
  data: {
    items: [
      {
        name: 'Brother打印机0',
        stepper: {
          stepper: 0,
          min: 0,
          max: 99
        },
      },
      {
        name: 'Brother打印机1',
        stepper: {
          stepper: 0,
          min: 0,
          max: 99
        },
      }
    ]
  },
  handleZanStepperChange(e) {
    console.log('stepper', e);
    var componentId = e.componentId;
    var stepper = e.stepper;

    this.setData({
      [`items[${componentId}].stepper.stepper`]: stepper
    });
  }
}))`

**Comment by youngjuning** [comment]
我已经实现过了。。

**Comment by DusuWen** [comment]
@hfxu 你的方式我用了不好使，改成这样就好使了
`this.setData({
      ['item[' +compoenntId+'].stepper.stepper']: stepper
    });`
