### ISSUE TITLE
select组件如何设置默认选中

### ISSUE THREAD

**Issue by sunshuaizhang** [youzan/zanui-weapp#129]
官方的例子里没找到设置select的默认选中方法，请问该如何实现。
<view class="zan-panel">
    <view>
      <template is="zan-select" data="{{ items, checkedValue: checked.base, componentId: 'base' }}" ></template>
    </view>
</view>

data: {
    items: [
      {
        padding: 0,
        value: '1',
        name: '选项一',
      },
      {
        padding: 0,
        value: '2',
        name: '选项二',
      },
    ],

    checked: {
      base: -1,
      color: -1,
      form: -1
    },

    activeColor: '#4b0'
},

**Comment by pangxie1991** [comment]
示例代码中，只要更改 checked 里面的数据为你需要的选中值的 value 就可以了
