### ISSUE TITLE
【疑问】在zanui-weapp中extend 和 assign的用法区别？

### ISSUE THREAD

**Issue by euii** [youzan/zanui-weapp#131]
在学习使用zanui的过程中，看到和tab下的index.js使用了extend来合并属性，而基本上其它的页面都使用了Oject.assign函数，我想知道的是，在zanui里这两个函数所使用场景有不同吗？如果有，能否可告知，到底哪些在调用哪些扩展的时候需要用assign，哪些需要 extend 呢？感谢

**Comment by pangxie1991** [comment]
在扩展过程中，部分组件需要用到生命周期。在 extend 函数里，会自动合并生命周期处理函数，所以可以直接使用 extend，对于非生命周期函数无影响
