### ISSUE TITLE
[新增功能] 自定义多列筛选栏

### ISSUE THREAD

**Issue by Cathon** [youzan/zanui-weapp#133]
想请教下类似于大众点评的这种多列筛选框该怎么写？
后期考不考虑添加这种组件？

![_20180224140445](https://user-images.githubusercontent.com/5621492/36626336-f12124aa-196b-11e8-9c0b-41d7628685bc.jpg)
![_20180224140451](https://user-images.githubusercontent.com/5621492/36626337-f17337a4-196b-11e8-9041-2332e19eefc6.jpg)

**Comment by pangxie1991** [comment]
暂时还没有加入这个组件的计划
