### ISSUE TITLE
zan-field 设置data-component-id无效, _handleZanFieldFocus事件中得不到该值

### ISSUE THREAD

**Issue by olive009** [youzan/zanui-weapp#138]
`<template is="zan-field" data-component-id="shit" data="{{ ...config.base.subType }}"></template>`

_handleZanFieldFocus事件输出: [zan:field:focus] **undefined** {value: ""}

**Comment by pangxie1991** [comment]
```html
<template is="zan-field" data="{{ componentId }}"></template>
```

所有的数据都是在 data 中传入
