### ISSUE TITLE
capsule建议优化下

### ISSUE THREAD

**Issue by q494492437** [youzan/zanui-weapp#143]
`<template name="capsule">
  <view class="zan-capsule zan-capsule--{{type}}">
    <block wx:if="{{color}}">
      <block wx:if="{{leftText}}">
        <view class="zan-capsule__left" style="background: {{ color }}; border-color: {{ color }}">{{ leftText }}</view>
      </block>
      <block wx:if="{{rightText}}">
        <view class="zan-capsule__right" style="color: {{ color }}; border-color: {{ color }}">{{ rightText }}</view>
      </block>
    </block>
    <block wx:else>
      <block wx:if="{{leftText}}">
        <view class="zan-capsule__left">{{ leftText }}</view>
      </block>
      <block wx:if="{{rightText}}">
        <view class="zan-capsule__right">{{ rightText }}</view>
      </block>
    </block>
  </view>
</template>
`
如果rightText 没写的话。。出来的效果比较奇怪。。

**Comment by q494492437** [comment]
上面是修改过的代码

**Comment by pangxie1991** [comment]
看了一下没有 rightText 的实际效果，确实很奇怪。
不过如果直接隐藏右边内容或者左边内容区域的话，样式其实并不是很好，样式调整后，其实也是一个 Tag 的样子~
所以在没有左侧内容或者右侧内容的时候，何不直接使用 Tag 组件呢~
