### ISSUE TITLE
Dialog弹窗层级问题

### ISSUE THREAD

**Issue by iyezhou** [youzan/zanui-weapp#147]
如图，弹窗显示input背景值，背景z-index已设置为-1，Dialog的z-index已设置为正数
![_20180314203930](https://user-images.githubusercontent.com/26378961/37402824-da73b456-27c7-11e8-8f43-6c51a86367f1.png)

**Comment by pangxie1991** [comment]
我这里看下~

**Comment by olive009** [comment]
还是显示input背景值，
使用自定义的样式为以下则OK

.zan-dialog--container{
  z-index: 2;
}

.zan-dialog--mask{
  z-index: 2;
}
