### ISSUE TITLE
如何设置表单Field的disabled和style

### ISSUE THREAD

**Issue by iyezhou** [youzan/zanui-weapp#148]
试了直接在标签中设置和config设置，都没有效果

**Comment by pangxie1991** [comment]
确实没有支持这个，我加下

**Comment by pangxie1991** [comment]
已经新增了 disabled 属性。 
style 传入是什么场景呢？想要了解下具体是需要定制哪一块的样式~

**Comment by iyezhou** [comment]
传入padding等属性

**Comment by pangxie1991** [comment]
可以，这样，我们最近也在切换 自定义组件，到时候会开放支持自定义 class 传入~

**Comment by pangxie1991** [comment]
![image](https://user-images.githubusercontent.com/5961240/39392010-e97b1242-4adf-11e8-9d67-c62202ca6aa5.png)

看了下，其实组件调整比较多的也是这种边框的地方。这种调整其实可以直接在 自定义组件 上设置样式调整，不需要外部 class 传入了

![image](https://user-images.githubusercontent.com/5961240/39392012-0a6280b2-4ae0-11e8-85ef-b0b6fe5eff9a.png)
