### ISSUE TITLE
使用中低端android机时::after等伪类显示问题

### ISSUE THREAD

**Issue by chengky** [youzan/zanui-weapp#153]
在中低端android机下，使用scroll-view组件，如果组件中使用zan-panel/zan-cell等使用::after伪类的组件时，上下快速滚屏时渲染空白。

**Comment by pangxie1991** [comment]
我明天用测试机试下~

**Comment by pangxie1991** [comment]
试了几个古老的安卓机，渲染没啥问题
能给下demo么~ 来个代码片段啥的，还有机型~

**Comment by chengky** [comment]
弄了个DEMO：https://github.com/chengky/zanui-issues-demo
测试的机型有：
小米红米NOTE 3 - MUI9.5
华为P8青春版

**Comment by pangxie1991** [comment]
ok，我周一去公司找机器试下~

不过，话说这个列表数据有点多，是不是考虑下屏幕外的节点回收啊~

**Comment by pangxie1991** [comment]
其实不是 :after 导致的，是使用 transform 导致的，低端安卓机显示的时候是会白一下再出来，暂时没有什么好方法优化了。

**Comment by chengky** [comment]
加上 will-change 部分机型改善很大，供碰到类似问题的朋友参考。

**Comment by pangxie1991** [comment]
这个手法可以~
