### ISSUE TITLE
能不能选择性的打包固定的组件 有些不一定用的到? 如何配置?

### ISSUE THREAD

**Issue by hevily** [youzan/zanui-weapp#173]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
目前还不支持这个
之后切换成自定义组件以后，会考虑支持小包发布功能。
不过现在建议还是直接引入整个大包~ 毕竟体积也不大~
