### ISSUE TITLE
Bug：项目编译完成后，用微信开发者工具打开报错

### ISSUE THREAD

**Issue by hxk1224** [youzan/zanui-weapp#179]
$ npm install
$ npm run dev

上面操作完成后，使用微信开发者工具打开报错：没有game.json
(unknown) Error: ENOENT: no such file or directory, open '/Users/zz_mac/Documents/WxApp/zanui-weapp-dev/example/game.json'
console.error

**Comment by hxk1224** [comment]
换了个目录重新操作了一遍，又没问题了

**Comment by 1983cc** [comment]
我用 cnpm 出现了这个问题，改用 npm 就好了
