### ISSUE TITLE
 *新增功能* 什么时候推出自定义头部，带返回首页的那种，感觉这个组件使用频率高，如果可以我想加入开发

### ISSUE THREAD

**Issue by lishuaixingNewBee** [youzan/zanui-weapp#18]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by chenjiahan** [comment]
本仓库已停止维护了，所以不会支持，sorry
