### ISSUE TITLE
Field中支持输入指定位数的小数吗？比如货币是2位小数，目前看了demo都是整数

### ISSUE THREAD

**Issue by wutianchow** [youzan/zanui-weapp#181]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
这个不支持，只是最基础的输入框功能，不过可以通过 input 回调来控制
