### ISSUE TITLE
多页面情况下，TopTips 无法自动清除

### ISSUE THREAD

**Issue by 0x01f7** [youzan/zanui-weapp#20]
重现步骤：

1. 标签页 A 持有一个 TopTips，并在 onLoad 时调用 showZanTopTips 
2. 标签页 B 持有一个 TopTips，并在 onLoad 时调用 showZanTopTips
3. 先点击标签页 A，可观察到 A 的 TopTips 正常显示
4. 再点击标签页 B，可观察到 B 的 TopTips 正常显示，并在三秒后自动隐藏
5. 再点击标签页 A，可观察到 A 的 TopTips 一直存在，不被自动清除

原因排查：

文件 /dist/toptips/index.js 中全局持有相同的 timer，而 data 数据由 Page 持有；导致第二次调用 showZanTopTips 时 timer 请重置，但前一个 Page 的 data 数据没有被重置。

解决方法：

参考 zantoast 的实现

**Comment by pangxie1991** [comment]
已修复~
