### ISSUE TITLE
tab 滚动的问题？

### ISSUE THREAD

**Issue by chaituan** [youzan/zanui-weapp#205]
当 scroll 设置为左右滚动的时候，  我selectedId 选中的是 最后一个选项，这个时候怎么自动滚动到选中的高亮位置。  现在是默认不滚动到选中位置。

**Comment by chaituan** [comment]
已解决

**Comment by eclanp** [comment]
请问下是怎么解决的啊？
我的情况是直接通过更改selectedId来改变，不是通过点击，怎么触发 _handleScroll() 呢？
