### ISSUE TITLE
表单无法提交数据

### ISSUE THREAD

**Issue by jiangyubao** [youzan/zanui-weapp#210]

**Comment by pangxie1991** [comment]
无法提交数据？ 是指 button 组件使用 submit 形式有问题么？
现在因为自定义组件的原因，自定义组件里的 button 里面设置 submit，点击后不会触发 form 的submit 了，这个暂时无解，需要推动微信了

如果不是这个，能描述下具体是什么情况下无法提交数据么？

**Comment by jiangyubao** [comment]
就是你们自带的field的例子，我把表单那段代码注释去除后，发现提交的表单内容为空。但是使用官方的例子就可以提交。暂时不清楚是你们的button问题，还是field问题。

**Comment by danyanp** [comment]
无解。。。。。我也遇到了

**Comment by pangxie1991** [comment]
field 自定义组件支持form 的submit 这个已经在进行了，预计下周三就行
button 自定义组件的 form-type=submit 形式下使用，点击以后无法触发外界 form 的 submit 事件，这个还要看下

**Comment by frankyoungd** [comment]
我猜这个需要微信来弄了，看起来自定义组件里的input，在form里是找不到的。这是个麻烦，如果采用bindblur这样的方式，会造成最后失去焦点的input，在你提交自之前，还没有触发onblur...后来没办法了，我就没用field了， 只是抄了field的模板和样式

**Comment by pangxie1991** [comment]
form 的 submit 这个是不行的，问了微信的人，这个他们考虑到 formid 可能被刷，所以暂时也不会开放这个

**Comment by wenlinguo** [comment]
@pangxie1991 

那如何解决提交表单问题呢？ 写小程序自己的button组件么？

**Comment by hqman** [comment]
@pangxie1991  打扰了  我在表单里面 放了一个 
```
 <van-button size="large" type="primary" formType="submit">登录</van-button>
```
submit 没反应。
