### ISSUE TITLE
Field 这个组件报错 ,VM9102:1 Page is not constructed because it is not found.

### ISSUE THREAD

**Issue by Naivetesun** [youzan/zanui-weapp#211]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
有具体的代码示例，或者代码片段么？ 我在 example 里面可以正常运行的

**Comment by Naivetesun** [comment]
Page(extend({}, {
  data: {
    field: {
      focus: true,
      title: '收货人',
      placeholder: '名字',
      value: 'test'
    }
  }
}));    官方文档这句话 加了extend()之后才会报错

**Comment by pangxie1991** [comment]
确实，这个是文档错了。切换成自定义组件以后，已经不需要 extend 了
