### ISSUE TITLE
zan-field 组件不支持数据绑定

### ISSUE THREAD

**Issue by olive009** [youzan/zanui-weapp#212]
zan-field的value只能获得初始值，更改后绑定值没有改变。

`<zan-field title="{{ config.form.name.title }}" 
placeholder="{{ config.form.name.placeholder }}" 
focus="{{ config.form.name.focus }}" 
error="{{ config.form.name.error }}" 
value="{{ name }}"></zan-field>`

**Comment by pangxie1991** [comment]
小程序不支持数据双向绑定的，field 提供了change 事件，在输入框内值改变时，可以通过这个监听到
