### ISSUE TITLE
zan-button点击事件不执行

### ISSUE THREAD

**Issue by qingdi** [youzan/zanui-weapp#215]
按zan的格式，不执行回调。
`<zan-button class="zan-pull-right" open-type="getUserInfo" bindgetuserinfo="getUserInfo" size="small">点击授权</zan-button>`
按原生格式，是没问题的。
`<button class="zan-pull-right" open-type="getUserInfo" bindgetuserinfo="getUserInfo" size="small">点击授权</zan-button>`

有bug。

**Comment by danyanp** [comment]
我也遇到了，怎么解决的

**Comment by pangxie1991** [comment]
这个会对现在的按钮的自定义组件做一个补充，支持按钮上各种类似 open-type 传入。
预计下周三会发个版本
