### ISSUE TITLE
Error 问题

### ISSUE THREAD

**Issue by olafchou** [youzan/zanui-weapp#216]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **
![2018-05-04 11 52 02](https://user-images.githubusercontent.com/19890798/39612393-a3b0324a-4f91-11e8-8495-a059b44f0784.png)

**Comment by pangxie1991** [comment]
你是跑的 demo 么？ 在跑之前需要执行 npm run dev

**Comment by olafchou** [comment]
我执行了 npm run dev ，还是不行

<img width="772" alt="2018-05-04 22 43 28" src="https://user-images.githubusercontent.com/19890798/39634227-cf1edf3e-4fec-11e8-92ab-312d1e1844fc.png">

**Comment by pangxie1991** [comment]
![image](https://user-images.githubusercontent.com/5961240/39660074-36420858-506a-11e8-9bc4-782507d9a28c.png)
我在 windows 和 mac 系统本地都新拉了一次组件库，运行正常，在小程序开发工具里也可以正常打开

你确认下，是否在 zanui-weapp 的根目录下执行的 npm run dev, node 和 npm 版本是否太古老了。。

**Comment by darkfiredarkhalo** [comment]
同样的问题:
node版本: 10.1.0
npm版本: 5.6.0
执行npm install 时,fsevents@1.1.3这个包无法下载,然后执行npm run dev 就会报:
fs.writeFileSync(fname, err.code.toString());
这个错,造成编译失败
