### ISSUE TITLE
程序员拉出去祭天

### ISSUE THREAD

**Issue by throneoftheGame** [youzan/zanui-weapp#218]
提交bug
![image](https://user-images.githubusercontent.com/20414295/39617408-374ebdee-4fb2-11e8-99ac-443bb38d4453.png)
npm install 安装包错误
# #217

**Comment by pangxie1991** [comment]
我在 windows 下试下。。。确实当时没试过 windows 。。

**Comment by throneoftheGame** [comment]
完美解决了，谢谢，npm降级成功安装运行
![image](https://user-images.githubusercontent.com/20414295/39687234-01791ef8-5200-11e8-8337-071226e60bed.png)
