### ISSUE TITLE
zan-ellipsis样式

### ISSUE THREAD

**Issue by chzjstar** [youzan/zanui-weapp#22]
需要设置固定宽度，如果设置width:100%就无效了；通常需求是需要宽度100%，所以建议在父元素加上width:0，就不需要设置固定宽度了。另外，通常会在列表中用到文字缩略显示，建议可以在列表中单独加入。
另：zanui-weapp可以多扩充一点，比如列表（两行内容，带头像列表），弹窗，表单等等，可以参考腾讯的frozenui

**Comment by pangxie1991** [comment]
我看了下，示例中需要设置width:300px是因为父级使用了flex布局，可以用max-width或者width：0搞定

扩充一点的话，如果平时遇到什么缺少的，可以给我们提issue或者直接pr~同时我们也会不断更新组件库~
列表（两行内容，带头像列表）可以通过cell实现，弹窗可以用Dialog，表单的又form~
