### ISSUE TITLE
请问一下，有没有旧版本的开发文档呢？

### ISSUE THREAD

**Issue by go522000** [youzan/zanui-weapp#220]
请问一下，有没有旧版本的开发文档呢？
因为刚刚好在五一前不久，使用了贵项目的进行开发，开发到一半了，不想换新版本，现在需要旧版本的开发文档进行参考。
请问哪里能看到旧版本的开发文档呢？如果没有在线版本的话，能不能发送到邮箱 go522000@126.com 一份给我呢，谢谢了。

**Comment by pangxie1991** [comment]
切换分支到 `old_code`, 在项目根目录下运行 `npm run watch:doc`，根据提示访问本地文档网站即可
![image](https://user-images.githubusercontent.com/5961240/39669941-125393d6-512c-11e8-8391-eaf1fa7241c4.png)

另外，邮件已发送

**Comment by Fairfarren** [comment]
lykwowlol@gmail.com请给我发一份，我clone了`old_code`发现时3.0.1的版本

**Comment by crossingAreed** [comment]
没有old_code分支 @pangxie1991 

git branch -a
* dev
  remotes/origin/HEAD -> origin/dev
  remotes/origin/dev
  remotes/origin/gh-pages
  remotes/origin/master
