### ISSUE TITLE
Stepper 计数器  事件报错

### ISSUE THREAD

**Issue by baitter** [youzan/zanui-weapp#221]
Stepper 计数器  事件报错
![image](https://user-images.githubusercontent.com/23312727/39681890-677550e4-51df-11e8-94f4-589b02dbfc50.png)

我打印componentId, stepper  都是underfind ，报错 stepper undefined

**Comment by throneoftheGame** [comment]
文档感觉有问题
![image](https://user-images.githubusercontent.com/20414295/39687267-2d395de6-5200-11e8-930d-d62a2569a4eb.png)

**Comment by pangxie1991** [comment]
这个是示例程序有问题，示例代码已经在 dev 上修复了

**Comment by yuu2lee4** [comment]
文档 里面size属性有哪些值没给出

**Comment by veking** [comment]
size：large | small | mini
