### ISSUE TITLE
zan-badge 中动态设置无效

### ISSUE THREAD

**Issue by fpl1104** [youzan/zanui-weapp#223]
<view class='order-detail'>
      <view class='order-item' wx:for='{{orderinfo}}' bindtap='{{item.bindtap}}'>
        <image src='{{item.img}}' class='item-image'></image>
        <zan-badge class='item-tip' wx:if='{{item.badge>0}}'>{{item.badge}}</zan-badge>
        <view class='item-name'>{{item.name}}</view>
      </view>

    </view>
{{item.badge}}程序中setdata已经改变,但是页面中没有改变

**Comment by pangxie1991** [comment]
已修复，本周会发一个新版~
