### ISSUE TITLE
我对这个bower等包管理器的东西不太熟，如果我直接把dist文件夹下的文件全部拖到我的工程里，可以用吗? bower好像自己都已经放弃了，首页上推荐别的😂

### ISSUE THREAD

**Issue by qingshanbugai** [youzan/zanui-weapp#23]
如题

**Comment by pangxie1991** [comment]
我对这个bower等包管理器的东西不太熟，如果我直接把dist文件夹下的文件全部拖到我的工程里，可以用吗? 
可以的，只要正确的引入文件，就可以用

bower好像自己都已经放弃了，首页上推荐别的
我们也支持通过npm方式引入~

**Comment by michaelzx** [comment]
如何做呢……

**Comment by pangxie1991** [comment]
node_modules 目录下的文件在小程序里面引用会有问题，所以需要 npm 安装完以后，重命名 node_modules 目录。
