### ISSUE TITLE
如何在wepy中通过npm引用zanui-weapp

### ISSUE THREAD

**Issue by fish0413** [youzan/zanui-weapp#232]
能提供相应的示例么，我这里js和wxss可以生成到dist中，json和wxml不知道怎么生成到dist里。

新手，对wepy如何引用第三方组件库不了解，如果zanui能有一个如何在wepy下使用的示例就好了。

**Comment by pangxie1991** [comment]
直接以自定义组件的形式引入就好了，新的组件库以自定义组件的形式来组织了

**Comment by HADB** [comment]
最好文档里能出个wepy项目的引用范例
