### ISSUE TITLE
cell中用for循环，为什么没有出现中间的边框？

### ISSUE THREAD

**Issue by lexiang** [youzan/zanui-weapp#234]
`<zan-panel class="cell-panel-demo" title="完成事项和记录">
  <zan-cell-group>
    <zan-cell title="{{daka[0].dakaName}}" value="{{daka[0].dakaText}}" is-link></zan-cell>
    <zan-cell title="{{daka[1].dakaName}}" value="{{daka[1].dakaText}}" is-link></zan-cell>
    <zan-cell title="{{daka[2].dakaName}}" value="{{daka[2].dakaText}}" is-link></zan-cell>
    <block wx:if="{{daka.length>0}}" wx:for="{{daka}}" wx:key="id">
      <zan-cell title="{{item.dakaName}}" value="{{item.dakaText}}" is-link></zan-cell>
    </block>
    <zan-cell wx:if="{{daka.length==0}}" title="还没有记录，赶紧记一笔吧！"></zan-cell>
  </zan-cell-group>
</zan-panel>`

前三项中间有边框， 用for循环后中间没有边框了

**Comment by lexiang** [comment]
<zan-panel class="cell-panel-demo" title="完成事项和记录">
  <zan-cell-group>
    <zan-cell title="{{daka[0].dakaName}}" value="{{daka[0].dakaText}}" is-link></zan-cell>
    <zan-cell title="{{daka[1].dakaName}}" value="{{daka[1].dakaText}}" is-link></zan-cell>
    <zan-cell title="{{daka[2].dakaName}}" value="{{daka[2].dakaText}}" is-link></zan-cell>
    <block wx:if="{{daka.length>0}}" wx:for="{{daka}}" wx:key="id">
      <zan-cell title="{{item.dakaName}}" value="{{item.dakaText}}" is-link></zan-cell>
    </block>
    <zan-cell wx:if="{{daka.length==0}}" title="还没有记录，赶紧记一笔吧！"></zan-cell>
  </zan-cell-group>
</zan-panel>

**Comment by pangxie1991** [comment]
我这里看下

**Comment by lexiang** [comment]
问题没有完全解决，如一楼中代码，把含数组daka[]的三个cell去掉，然后再重复一遍整个代码，则只有第一次循环能显示边框，第二次就又没有了。
`<zan-panel class="cell-panel-demo" title="完成事项和记录">
  <zan-cell-group>
    <zan-cell wx:if="{{daka.length>0}}" wx:for="{{daka}}" wx:key="id" title="{{item.dakaName}}" value="{{item.dakaText}}" is-link></zan-cell>
    <zan-cell wx:if="{{daka.length==0}}" title="还没有记录，赶紧记一笔吧！"></zan-cell>
  </zan-cell-group>
</zan-panel>`
