### ISSUE TITLE
zan-button用于提交表单

### ISSUE THREAD

**Issue by Javonmeng** [youzan/zanui-weapp#241]
普通button可以直接提交表单，zan-button中加上form-type="submit"无法触发表单处理函数

**Comment by pangxie1991** [comment]
zan-button 使用自定义组件构成。微信对于自定义组件内部按钮设置 form-type 的，屏蔽了其 submit 功能。
目前没啥好的解决方案，如果需要 button 的 submit/reset 功能，暂时只能使用原生的
