### ISSUE TITLE
如何使用yarn或者npm管理

### ISSUE THREAD

**Issue by tim0991** [youzan/zanui-weapp#242]
希望能够尽量简单的安装和更新。

同时小程序有2M的大小限制，如果上述要求不行的话 直接引入整个包如何避免超过大小限制问题？
如果可以通过包管理引入的话 又如何解决这个问题，可以尽可能只引入需要的文件

**Comment by hgq520** [comment]
+1

**Comment by tim0991** [comment]
我用yarn 安装之后使用package的钩子解决了。。。但是不知道姿势对不对

**Comment by pangxie1991** [comment]
组件库现在在 npm 和 bower 上都有，如果已经在项目中引入框架或者自己已经设置打包，那么可以通过 npm 的形式引入。如果没有的话，可以使用 bower 形式引入
关于包大小，组件库目前已最简单的形式提供的，引入的话只需要引入 dist 目录就好了

**Comment by cafehaus** [comment]
> 希望可以像 蘑菇街的minui一样，支持按需引入

vant和小程序官方都不支持的，可以使用 npm 包：vant-tree-shaking 来实现按需引入，使用文档 https://www.npmjs.com/package/vant-tree-shaking
