### ISSUE TITLE
cell 页面跳转问题

### ISSUE THREAD

**Issue by baitter** [youzan/zanui-weapp#244]
![111](https://user-images.githubusercontent.com/23312727/40048015-b6717efe-5863-11e8-9cad-49eb037f3476.png)
这是文档上页面跳转，直接在is-link后面加地址，可是实际跳不过去
正确的应该是在url后面写地址
![default](https://user-images.githubusercontent.com/23312727/40048122-fb5331a2-5863-11e8-9849-8039488fc4e9.png)

**Comment by throneoftheGame** [comment]
确实存在文档问题

**Comment by pangxie1991** [comment]
收到，这个我修复下文档
