### ISSUE TITLE
不支持三目运算

### ISSUE THREAD

**Issue by baitter** [youzan/zanui-weapp#245]
老铁，我又来了
废话不多说，直接上图
![11](https://user-images.githubusercontent.com/23312727/40092629-c5dec09e-58f0-11e8-9caf-43bf270ab231.png)
直接报错

**Comment by baitter** [comment]
![default](https://user-images.githubusercontent.com/23312727/40092649-edf8a716-58f0-11e8-9ffb-29c3428e8add.png)

**Comment by throneoftheGame** [comment]
小程序原生标签就可以使用三目运算符，zan-cell会报错

**Comment by pangxie1991** [comment]
![image](https://user-images.githubusercontent.com/5961240/40238474-dcb12612-5ae5-11e8-942f-e0757a5f78f5.png)
![image](https://user-images.githubusercontent.com/5961240/40238487-e519700c-5ae5-11e8-98d9-753beed23acc.png)

我这里试了下能够正常展示的，是不是在代码里使用了中文字符什么的导致报错了？
如果不行的话，方便发个代码片段么？
