### ISSUE TITLE
demo在微信开发者工具运行不起来哦，报错

### ISSUE THREAD

**Issue by zzw118** [youzan/zanui-weapp#248]
demo在微信开发者工具运行不起来哦，报错
![image](https://user-images.githubusercontent.com/9132607/40108137-b1da85ba-592c-11e8-9b61-0e0ae249244a.png)

**Comment by pangxie1991** [comment]
在运行 demo 之前，需要先编译。在根目录运行 npm run dev 即可

**Comment by zzw118** [comment]
搞定了，谢谢
