### ISSUE TITLE
自定义组件传值的疑问

### ISSUE THREAD

**Issue by Joey630803** [youzan/zanui-weapp#250]
components里我定义了下拉选择框组件，然后又定义了搜索框组件，我要根据下拉框的值来搜索，所以组件之间如何传值呢？或者应该叫自定义模板，还是说这东西需要一个像redux一样的工具来管理全局状态？

**Comment by pangxie1991** [comment]
需要你在两个组件外，再包一个父组件或者就是页面，通过页面来共享数据
现在的组件基本都是受控组件，只要改变数据即可
