### ISSUE TITLE
mpVue 中可以使用吗

### ISSUE THREAD

**Issue by wzx3015** [youzan/zanui-weapp#252]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
只要支持自定义组件，就可以使用。不过貌似 mpvue 还不支持自定义组件
