### ISSUE TITLE
小写字母x被替换成一个小图标

### ISSUE THREAD

**Issue by likino** [youzan/zanui-weapp#256]
小写字母x被替换成一个小图标, 如图:
![image](https://user-images.githubusercontent.com/11705143/40277288-eef28fea-5c4e-11e8-854e-ffa0f606fa3a.png) 
![image](https://user-images.githubusercontent.com/11705143/40277284-da282d0e-5c4e-11e8-86c7-6fa0b25717bd.png)

**Comment by pangxie1991** [comment]
这个是不是不是英文的 x，而是一个奇怪的字符。zanui 不影响这种展示的
