### ISSUE TITLE
cell，bindtap问题

### ISSUE THREAD

**Issue by zhfish** [youzan/zanui-weapp#258]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **
提交bug
** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **
bindtap之后，点击cell自身会进入两次handle
第一次是cell组件调用
第二次是view自身的tap事件
点击footer部分，因为不触发view的tap事件，所以只进入一次handle

目前cell的bindtap，必须和onlyTapFooter一起使用才算正常

**Comment by pangxie1991** [comment]
收到，确实是个问题。我们这里尽快改下
