### ISSUE TITLE
复杂组件怎么用呢

### ISSUE THREAD

**Issue by xrfinbupt** [youzan/zanui-weapp#26]
普通页面在这种架构下面加东西
Page({

  /**
   * 页面的初始数据
   */
  data: {
  
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {
  
  },

复杂组件：
Page是这样的

Page(
  Object.assign({}, Zan.Switch, {
}

他们之间怎么兼容处理呢，谢谢

**Comment by pangxie1991** [comment]
object.assign 只是对象的合并，zan里面的一些方法混入到原来的大对象里
你可以在第三个object里面写自己想要的方法
```javascript
Page(Object.assign({}, Zan.switch, {
    /**
     页面的初始数据
    */
    data: {},
    /**
     生命周期函数--监听页面加载
    */
    onLoad(options) {}
}))
```
