### ISSUE TITLE
Steps的className无效

### ISSUE THREAD

**Issue by yuu2lee4** [youzan/zanui-weapp#266]
自定义组件应该使用外部样式类的方式

**Comment by yuu2lee4** [comment]
建议右侧的内容使用slot的方式插入

**Comment by yuu2lee4** [comment]
还有zan-steps__icons 有个白色背景，对非白色的容器非常不友好

**Comment by jerryni** [comment]
@yuu2lee4 className是可以用的，然后你可以通过覆盖zan-steps__icons background-color的方式来写。 可以贴下你的使用方法

**Comment by yuu2lee4** [comment]
@jerryni   自定义组件无法通过外部类来改样式 必须组件声明内部类

**Comment by jerryni** [comment]
@yuu2lee4 哦，那看来还是要提供属性了，我后面修下
