### ISSUE TITLE
tab标签的scroll属性无效，有bug

### ISSUE THREAD

**Issue by Gitsifu** [youzan/zanui-weapp#267]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by Gitsifu** [comment]
`
<view style="margin: 0 0 40rpx 0">
    <zan-tab list="{{ tab.list }}" selected-id="{{ tab.selectedId }}" scroll="true" fixed="true" bindtabchange="customCallback" />
  </view>
`

// js
`
  data: {
    //tab列表
    tab: {
      list: [
        {
          id: 1,
          title: '待取'
        },
        {
          id: 2,
          title: '已取'
        },
      ],
      selectedId: 1
    },
  },
`

**Comment by Gitsifu** [comment]
不加scroll="true"是这样的：

![image](https://user-images.githubusercontent.com/23445650/40461769-80a7081a-5f3f-11e8-8483-9032d90a3be9.png)


添加完scroll="true"后就变成下面这样的了

![image](https://user-images.githubusercontent.com/23445650/40461658-fdce0f9c-5f3e-11e8-94e9-3db2cdc3d6ce.png)

**Comment by Gitsifu** [comment]
真机上正常显示，估计是模拟器的不兼容吧

**Comment by rex-zsd** [comment]
设置了`scroll`和`fixed`以后，因为内部使用的ScrollView高度设置的是auto，实际高度可能会意外地不符合预期。建议传个`height="44"`把高度固定下来。
后续可能会做下优化。
