### ISSUE TITLE
noticebar 通告栏组件使用报错

### ISSUE THREAD

**Issue by zzw118** [youzan/zanui-weapp#268]
报的这个错，有人遇到过吗？

**Error: 页面缺少 noticebar 元素**

**Comment by pangxie1991** [comment]
你是怎么使用的？有 代码片段 或者贴段代码上来？

**Comment by veking** [comment]
@zzw118 看提示信息像是缺少元素，检查一下 wxml 文件是否有 zan-noticebar 元素定义。

**Comment by zzw118** [comment]
@veking 
![image](https://user-images.githubusercontent.com/9132607/40472515-4946405c-5f6c-11e8-98c9-12f5b0c9b645.png)
有定义的，报错，然后内容没有出来

**Comment by jerryni** [comment]
@zzw118 https://www.youzanyun.com/zanui/weapp#/zanui/view/noticebar 看下和文档有什么出入没~

**Comment by zzw118** [comment]
@jerryni 按照文档来的啊，其他组件ok的

**Comment by yishangfei** [comment]
我也想反映这个问题
![image](https://user-images.githubusercontent.com/15099278/41073599-9f0dfce4-6a36-11e8-8c40-34968ccafe8b.png)我的没有像你这样报错     就是没data的值没有设置默认值  如果设置默认值 网络获取再修改 就会先闪一下的bug    不知这个改如何处理

**Comment by rex-zsd** [comment]
@zzw118 [组件内部](https://github.com/youzan/zanui-weapp/blob/dev/packages/noticebar/index.js#L93)有判断content部分的宽度。
看下你绑定的text初始值是不是空的。
