### ISSUE TITLE
demo无法运行,run-dev报错

### ISSUE THREAD

**Issue by darkfiredarkhalo** [youzan/zanui-weapp#271]
node版本: 10.1.0
npm版本: 5.6.0
执行npm install 时,fsevents@1.1.3这个包无法下载,然后执行npm run dev 就会报:
fs.writeFileSync(fname, err.code.toString());
这个错,造成编译失败

**Comment by darkfiredarkhalo** [comment]
node版本升级至10.2,0,npm升级至6.0.1,重新安装编译,依旧报错

**Comment by Gitsifu** [comment]
使用cnpm试一下吧，npm 因为 网络的原因可能会下载超时

**Comment by rex-zsd** [comment]
境内npm还是建议使用[淘宝源](https://npm.taobao.org/)吧，包没有下全报错也是正常的。
