### ISSUE TITLE
Popup 里套scrollView，与默认全屏的滚动冲突

### ISSUE THREAD

**Issue by hanwenbo** [youzan/zanui-weapp#272]
BUG

问题描述：

> Popup 里套scrollView，与默认全屏的滚动冲突
我做的是商品详情的下面弹出规格列表，由于规格列表内容多 需要加scrollView，那么问题来了，你会发现你很容易出发与默认的window的滚动条冲突  俩一起滑动，或者window的没结束 你再去滑动自定义区域的scrollView ，window的滚动优先  导致无法正常工作

**Comment by pangxie1991** [comment]
是的，这个是滚动穿透了。这个目前也只能在全局通过 css 屏蔽整个页面的滚动来做了

**Comment by hanwenbo** [comment]
@pangxie1991 微信官方bug是吧

**Comment by pangxie1991** [comment]
不是 bug，目前微信也没提供方法，禁止背后的屏幕滚动，所以没办法。只能通过 css 禁止
