### ISSUE TITLE
tab组件宽度问题

### ISSUE THREAD

**Issue by yuu2lee4** [youzan/zanui-weapp#277]
里面写死了width: 750rpx 不太友好

**Comment by pangxie1991** [comment]
750rpx 为了占满屏幕，是有什么场景需要么？

**Comment by yuu2lee4** [comment]
有这种设计图 左边是tab  右边是其它的一些元素 没办法 /(ㄒoㄒ)/~~  tab建议width 100%

**Comment by Airkro** [comment]
tab组件不满屏的需求还是很常见的，而且从组件设计的角度来说用100%也更合理
