### ISSUE TITLE
noticebar的text如果是动态加入，noticebar会不滚动

### ISSUE THREAD

**Issue by lwpassvoice** [youzan/zanui-weapp#279]
**请确认是需要 *新增功能* 还是 *提交bug* **
提交bug
** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **
```
	<zan-noticebar
		text="{{msgs}}"
		backgroundColor="transparent"
		color="#666"
		leftIcon="/img/bell.png"
		scrollable="true">
		</zan-noticebar>
```

msgs初值很短，重设的值很长，noticebar没滚动

**Comment by pangxie1991** [comment]
是的，这个地方要加强下

**Comment by chengaobin** [comment]
这个问题还是存在，一开始的值很长，有时候也不滚动
