### ISSUE TITLE
npm run dev finished build后长时间没反应 编译不成功

### ISSUE THREAD

**Issue by godhelpjun** [youzan/zanui-weapp#282]
d:\youzan\zanui-weapp>node -v
v8.11.2

d:\youzan\zanui-weapp>npm -v
5.6.0
D:\youzan\zanui-weapp>npm install
npm WARN rm not removing D:\youzan\zanui-weapp\node_modules\.bin\color-support.cmd as it wasn't installed by D:\youzan\zanui-weapp\node_modules\_color-support@1.1.3@color-support
npm WARN rm not removing D:\youzan\zanui-weapp\node_modules\.bin\color-support as it wasn't installed by D:\youzan\zanui-weapp\node_modules\_color-support@1.1.3@color-support
npm WARN eslint-config-airbnb@16.1.0 requires a peer of eslint-plugin-react@^7.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

removed 19 packages and updated 48 packages in 22.935s

> zanui-weapp@3.0.3 dev D:\youzan\zanui-weapp
> node scripts/build-dev.js --color

[14:31:13] Working directory changed to D:\youzan\zanui-weapp\scripts\utils
[14:31:14] Using gulpfile D:\youzan\zanui-weapp\scripts\utils\build.js
[14:31:14] Starting 'compile-css'...
[14:31:14] Starting 'compile-js'...
[14:31:16] Finished 'compile-js' after 2.15 s
[14:31:16] Finished 'compile-css' after 2.34 s
[14:31:16] Starting 'build'...
[14:31:16] Finished 'build' after 49 μs

**Comment by pangxie1991** [comment]
npm run dev 是调试模式，开了 watch 的。
所以在 Finished xxx 出来以后，已经完成了当次编译
