### ISSUE TITLE
date-picker的value无效

### ISSUE THREAD

**Issue by BadmintonCode** [youzan/zanui-weapp#286]
看到文档里value的类型是null，有点不太理解，如果无法给date-picker赋值，那这个组件岂不是只能在流程中使用一次，不知道是bug还是我的使用方式不对
我是传了一个日期进去 如2018-02-03

**Comment by BadmintonCode** [comment]
还发现一个问题，就是如果是从网络获取数据，那么因为已经渲染过了，无法把最后的value给到组件里

**Comment by BadmintonCode** [comment]
目前的做法是加在placeholder里，但是date-picker作为一个比较可能出现在表单中的组件，value和name可以考虑一下

**Comment by presleylee** [comment]
最新版试了，确实是无效啊。

**Comment by realywithoutname** [comment]
文档有错，请使用 date 属性。这个组件接下会做一些优化。
