### ISSUE TITLE
引入popup后，点击遮罩层关闭不了

### ISSUE THREAD

**Issue by Wade-Lu** [youzan/zanui-weapp#292]
是不是还要加上什么属性或者事件

**Comment by rex-zsd** [comment]
@Wade-Lu 有示例代码可以贴一下吗
设置了closeOnClickOverlay为true应该点击遮罩层就可以关闭的

**Comment by haolijing** [comment]
在mpVue中引入van weapp   点击蒙层 蒙层不消失。
<van-popup :show="showPop" :closeOnClickOverlay="true">内容</van-popup>
