### ISSUE TITLE
button组件在禁用时仍然会触发点击事件

### ISSUE THREAD

**Issue by Airkro** [youzan/zanui-weapp#297]
`<zan-button disabled />`

虽然样式上是禁用的，但是却仍然可以点击并触发事件。
原因是内部的原生button没有应用disabled属性。
既不符合设计原则，也容易造成问题，望修改。

**Comment by rex-zsd** [comment]
目前绑定的事件是`btnclick`，你反应的触发的事件应该是`tap`吧，改到`btnclick`应该就可以了。
不过目前这样处理的确是有点反直觉，后面可能会做下优化。

**Comment by LauJon** [comment]
该问题现在依然存在

**Comment by LauJon** [comment]
> 目前绑定的事件是`btnclick`，你反应的触发的事件应该是`tap`吧，改到`btnclick`应该就可以了。
> 不过目前这样处理的确是有点反直觉，后面可能会做下优化。

该问题现在依然存在

**Comment by teri5354** [comment]
目前是0.5.2版本，问题仍然存在

**Comment by li-xunhuan** [comment]
目前最新版问题依然在~~

**Comment by bearDream** [comment]
0.5.16仍然存在该问题.....

**Comment by herock** [comment]
当用于获取用户信息时 open-type="getUserInfo"，怎么禁用呢？
