### ISSUE TITLE
field表单数据获取的问题

### ISSUE THREAD

**Issue by mao6** [youzan/zanui-weapp#300]
field的value属性不支持双向数据绑定吗？在输入框中输入信息之后绑定的变量值没有改变，赋初值是可以的，谁能告诉我该怎么办？

**Comment by BadmintonCode** [comment]
bind:change监听

**Comment by rex-zsd** [comment]
小程序目前不支持双向绑定的
可以自己监听bind:change事件设置值
可以参考[组件文档](https://www.youzanyun.com/zanui/weapp#/zanui/form/field)

**Comment by shidiyanmo** [comment]
data: {
    field: {
      focus: true,
      title: '收货人',
      placeholder: '名字',
      value: 'test'
    }

handleFieldBlur(e) {
      console.log(this.field.value);
    }
报错  很恶心
