### ISSUE TITLE
请问 如何在各自页面里覆盖组件样式

### ISSUE THREAD

**Issue by dajiza** [youzan/zanui-weapp#301]
请问我在一个页面里面引用了某组件，我想在这个页面中对组件做一些样式覆盖，因为有#shadow-root的关系，正常写的css没有用
请问有什么方法可以做到？

**Comment by jerryni** [comment]
用这个属性：externalClasses
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html

**Comment by suzi404** [comment]
完全不能覆盖。。。使用了externalClasses功能，样式上还加了!important，但是完全不受影响。。。我不知道完全不能修改的ui库到底有啥用，这5000多个start是怎么来的

**Comment by rex-zsd** [comment]
@dajiza 升级到自定义组件以后文档这块还没补上。大多数组件都会对外暴露一些externalClasses，以[Cell组件](https://github.com/youzan/zanui-weapp/blob/dev/packages/cell/index.js#L7)为例

**Comment by rex-zsd** [comment]
@suzi404 如果有影响使用的问题可以贴jsfiddle或者代码截图反馈，如果定制需求比较强可以新开issue反馈。

**Comment by rex-zsd** [comment]
#243

**Comment by rex-zsd** [comment]
跟 #243 重复了，可以关注下那个issue
