### ISSUE TITLE
DatetimePicker 时间选择初始化获取不到时间

### ISSUE THREAD

**Issue by liberty-m** [youzan/zanui-weapp#302]
DatetimePicker 时间选择初始化获取不到时间
信息都为0

**Comment by liberty-m** [comment]
我value传入的是date 
date: new Date()
绑定{{date}}
value传不传在真机都不能获取到默认时间 无法滚动

**Comment by realywithoutname** [comment]
date 属性只支持可以被 new Date 支持的 String 类型数据
