### ISSUE TITLE
加载资源报错

### ISSUE THREAD

**Issue by Yi-Lyu** [youzan/zanui-weapp#303]
![image](https://user-images.githubusercontent.com/1308846/41271412-0efdeb9e-6e43-11e8-927b-9b1306cad7ce.png)

https://b.yzcdn.cn/zanui-weapp/zanui-weapp-icon-eeb0d3c52a.woff2

**Comment by jerryni** [comment]
应该是网络问题

**Comment by bftree123** [comment]
> ![image](https://user-images.githubusercontent.com/1308846/41271412-0efdeb9e-6e43-11e8-927b-9b1306cad7ce.png)
> 
> https://b.yzcdn.cn/zanui-weapp/zanui-weapp-icon-eeb0d3c52a.woff2

请问解决了吗？我也是这个问题

**Comment by qiuyoo** [comment]
小程序需要 授权访问资源 IP。 百度一下
