### ISSUE TITLE
[新增功能] Field 输入框 可否提供设置高度和宽度的属性

### ISSUE THREAD

**Issue by Sean-Wang** [youzan/zanui-weapp#304]
"zan-field": "path/to/zanui-weapp/dist/field/index"

Field 输入框

可否提供设置高度和宽度的属性？

**Comment by rex-zsd** [comment]
@Sean-Wang Field组件有提供externalClasses field-class
可以参考一下[官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB)

**Comment by Sean-Wang** [comment]
@rex-zsd 谢谢，已解决。
