### ISSUE TITLE
[新增功能]Tab标签自动滑动

### ISSUE THREAD

**Issue by firstpersonl** [youzan/zanui-weapp#307]
### Tab标签自动滑动。

在激活tab标签时，选择的标签自动滑动到中间位置

**Comment by songGuangHui** [comment]
我用原生小程序开发，用的van-tabs和van-tab，并没有这个效果，用mpvue开发的就有这个效果，这是为什么呢？我审查元素scroll-view的scroll-left确实有值，vant-weapp是刚从git上拉下来的
![image](https://user-images.githubusercontent.com/30467546/50628262-521f9280-0f72-11e9-9b24-0add4777d7f4.png)
![image](https://user-images.githubusercontent.com/30467546/50628324-9d39a580-0f72-11e9-95d5-e5da4c81f969.png)

**Comment by songGuangHui** [comment]
知道了，引入的wxParse设置的overflow: auto;造成该效果失效
