### ISSUE TITLE
用`mpvue`写了一个使用`zanui`的示例，原生组件引入，基本不修改官方代码

### ISSUE THREAD

**Issue by JJJYY** [youzan/zanui-weapp#308]
目前没发现什么大问题，仅供参考  
项目改写自官方示例，只是手动将`toptips`方法从组件抽离，以防止页面的多次注册，其他部分并未修改源码

[项目地址](https://github.com/JJJYY/mpvue-zanui)
[插件地址](https://github.com/JJJYY/import-weapp-component)

这个算打广告么～～

**Comment by jerryni** [comment]
兄弟你的广告方式不对，应该在别人有需求的情况再留言里打，先关了

**Comment by JJJYY** [comment]
@jerryni ,抱歉
