### ISSUE TITLE
下载项目到本地，复制dist的文件到项目里报错

### ISSUE THREAD

**Issue by featnet** [youzan/zanui-weapp#316]
![image](https://user-images.githubusercontent.com/23646120/41708217-8b478ac6-7572-11e8-8820-a559c2e213fe.png)

请问可以这样使用吗

**Comment by rex-zsd** [comment]
使用的代码可以贴一下吗？

**Comment by featnet** [comment]
![image](https://user-images.githubusercontent.com/23646120/41709713-785d03ce-7576-11e8-9e6c-02538eba224e.png)
把dist目录复制到项目里的。

**Comment by rex-zsd** [comment]
给出的信息太少了，不知道你怎么用的，很难定位到你的问题。
正常使用dist里的组件应该是没问题的。

**Comment by featnet** [comment]
![image](https://user-images.githubusercontent.com/23646120/41769634-8d5ab786-7642-11e8-8476-e0c502226e66.png)
在这里下载后解压，然后复制dist目录到项目里就会报错

**Comment by pangxie1991** [comment]
我这里试了下，直接在项目里面拷贝进去没有报错出现
在引用 btn 组件后，也没有报错
![image](https://user-images.githubusercontent.com/5961240/42197187-2fcc1090-7eb4-11e8-99f1-2caef4ee34a7.png)
![image](https://user-images.githubusercontent.com/5961240/42197194-37136e16-7eb4-11e8-890e-c69470ce2c7e.png)
![image](https://user-images.githubusercontent.com/5961240/42197197-3b5c4a9c-7eb4-11e8-9179-ec1e542f0b10.png)

这个 behavior 的报错，是不是基础库版本选的太低了~

**Comment by featnet** [comment]
可以了，是基础库版本太低。谢啦
