### ISSUE TITLE
在自定义组件中引入报错

### ISSUE THREAD

**Issue by Yuliang-Lee** [youzan/zanui-weapp#317]
目前组件只能在 page 里引用，不能在自定义组件里使用吗?

![image](https://user-images.githubusercontent.com/6936358/41754033-328fc150-7603-11e8-8f2e-982077bd07a0.png)

**Comment by rex-zsd** [comment]
可以在自定义组件里使用的。
使用的代码块方便贴下吗？

**Comment by Yuliang-Lee** [comment]
我像 Toast 那样，把 export 的 `Toptips` 放到单独的文件使用就可以了，

![image](https://user-images.githubusercontent.com/6936358/41755694-39841bfc-760b-11e8-936f-873193213f5b.png)

还有，如果在组件中使用，引入的 wxml 块不能放在自定义组件的 wxml 里，要放在 page 的 wxml 里。

**Comment by Yuliang-Lee** [comment]
这个代码的修改和文档的补充，我可以提 PR 吗

**Comment by rex-zsd** [comment]
可以呀 欢迎PR
