### ISSUE TITLE
新增功能：noticebar的 left-icon 可以跟文字一起滚动

### ISSUE THREAD

**Issue by Rooaw** [youzan/zanui-weapp#319]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by rex-zsd** [comment]
@Rooaw 目前noticeBar的left-icon是不随文字一起滚动的，你的意思是想支持可以一起滚动是吗？

**Comment by Rooaw** [comment]
是的

**Comment by rex-zsd** [comment]
目前暂没有这个计划呢。。。
