### ISSUE TITLE
提交bug： <zan-field>组件下莫名出现一条线

### ISSUE THREAD

**Issue by Rooaw** [youzan/zanui-weapp#320]
index.json文件:
`{
    "usingComponents": {
        "zan-field": "/dist/field/index"
    }
}`
index.wxml文件：`
 <zan-field>
        </zan-field>`

新初始化的小程序项目，其他都没动，就添加了 field 组件

**Comment by rex-zsd** [comment]
可以截个图吗？看下具体是什么效果

**Comment by Rooaw** [comment]
![66ba2342e7c9bb55416880ef1633a59](https://user-images.githubusercontent.com/15188374/41890404-f2bf8f5a-7941-11e8-8e09-4fb4c86c7533.png)
上面两个是原生写的，红色框是 zan-field 组件渲染的，下面有一条线，而且这条线会相对 input 往右偏移一点，

**Comment by rex-zsd** [comment]
@Rooaw 正常使用是会在下面有一条线的，而且目前暂不支持通过配置来隐藏这条线。
但是把field包在cell-group组件内使用时，最后一个field会隐藏这条线。
所以可以试下
```
<zan-cell-group>
      <zan-field title="" value=""></zan-field>
</zan-cell-group>
```
