### ISSUE TITLE
popup在iphone上出现空白

### ISSUE THREAD

**Issue by NoddyLiu** [youzan/zanui-weapp#322]
测试机器：iphone 6p，iphone se，一加5t
问题，底部popup在iphone上会显示不全，空白，例如
![1529988794 1](https://user-images.githubusercontent.com/2139979/41889979-ed9bea66-793f-11e8-8b66-debd78421a0a.jpg)

但一加5t就没有这个问题，
![51bd514ccf02c04e005924f17d041d7](https://user-images.githubusercontent.com/2139979/41889933-b82f2ba4-793f-11e8-944a-fe90a37c0354.jpg)

**Comment by jerryni** [comment]
上个代码吧，最好能提供个fiddle，重现下

**Comment by NoddyLiu** [comment]
我找到原因了，只要最顶层是用<scroll-view scroll-y/> ，iphone就会出现底部popup空白的情况，而android就没有这种问题。我只能换回最顶层<view/>
