### ISSUE TITLE
Button组件无法自定义按钮的点击效果

### ISSUE THREAD

**Issue by xianer0405** [youzan/zanui-weapp#326]
Button组件无法自定义按钮的点击效果。
*提交bug* **

** 例如我简单引用一个按钮：
<zan-button type="primary">确认付款</zan-button>
1.在手机上预览,点击该按钮,无法体现交互效果
2.原生的小程序Button组件,是有点击效果的(背景色的变化),而且提供了hover-class来自定义点击效果.

请问为何没有支持该特性,  是否能够支持该特性呢?

**Comment by jerryni** [comment]
#287

**Comment by jerryni** [comment]
#275 重复
