### ISSUE TITLE
TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by leavenotrace** [youzan/zanui-weapp#327]
zanui-weapp git:(dev) ✗ npm audit fix
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN eslint-config-airbnb@16.1.0 requires a peer of eslint-plugin-react@^7.4.0 but none is installed. You must install peer dependencies yourself.

+ wedoc@0.0.17
+ gh-pages@1.2.0
added 9 packages from 4 contributors, removed 1 package and updated 4 packages in 13.47s
fixed 85 of 95 vulnerabilities in 38509 scanned packages
  1 package update for 10 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or do it by hand)
➜  zanui-weapp git:(dev) ✗ npm run dev

> zanui-weapp@3.0.4 dev /Users/bobzheng/Documents/Code/wechat/zanui-weapp
> node scripts/build-dev.js --color

[10:51:11] Working directory changed to ~/Documents/Code/wechat/zanui-weapp/scripts/utils
gulp[1455]: ../src/node_contextify.cc:629:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x8399028427d
/private/var/folders/58/cgcfbhz10xs2gw8zqp8jzzfr0000gn/T/shelljs_461429abe41eff121c34:10
    fs.writeFileSync(fname, err.code.toString());
                                     ^

TypeError: Cannot read property 'toString' of null
    at /private/var/folders/58/cgcfbhz10xs2gw8zqp8jzzfr0000gn/T/shelljs_461429abe41eff121c34:10:38
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
exec: internal error

**Comment by rex-zsd** [comment]
@leavenotrace 
node v10.0.0 is buggy with gulp v3.9, downgrade node to v9.0.0 could resolve this.
[#20285](https://github.com/nodejs/node/issues/20285#issuecomment-387612673)
