### ISSUE TITLE
actionsheet组件分享按钮点击后 屏幕蒙层 会遮挡分享时的截图，这个怎么处理？*提交bug* 

### ISSUE THREAD

**Issue by Markxuxiao** [youzan/zanui-weapp#328]
使用actionsheet 分享功能
{
      name: '去分享',
      openType: 'share'
 }
屏幕蒙层 会遮挡分享时的截图

我现在的解决办法
onShareAppMessage: function (res) {
      for(let i=0; i<99;i++){
        this.closeActionSheet()
      }
      return {
        title:’name‘
        path: '/pages/share/index‘
      }
 }

this.closeActionSheet()  写一次 会有一定几率还是被遮挡，我分析可能是渲染和截图是2个线程，渲染还未完成，截图就执行了。使用我让onShareAppMessage执行时间长一点等待渲染完了再返回执行截图
请问有更好的解决方案么，还是能修改这个组件逻辑避免这个问题

**Comment by rex-zsd** [comment]
有截图什么的吗？

**Comment by pangxie1991** [comment]
微信默认是在分享的时候直接截取图片的，所以在 actionsheet 弹出来的时候，截图会出现黑背景。
一般常用的做法，会在 onShareAppMessage 这个方法里面返回的内容，把需要分享的图片链接也返回，而不是采用微信默认的截图功能

**Comment by Markxuxiao** [comment]
返回图片这个接口我肯定知道啊，特殊场景，比如是图片和数据我都要截屏，难道要后台生成一张图吗？这样就不合理了吧

**Comment by lopaz** [comment]
现在onShareAppMessage里支持promise，加点延迟就好了
