### ISSUE TITLE
小程序演示缺少一些组件

### ISSUE THREAD

**Issue by yuu2lee4** [youzan/zanui-weapp#330]
比如loadmore datetime-picker
话说发布了3.0.5 但是dist没更新？

**Comment by pangxie1991** [comment]
ok，小程序审核通过以后就会有
loadmore 是故意没有放出来，暂时会弱化他的存在。需要考虑下这个东西具体应该是什么样子的，和 loading 的差距在哪里

3.0.5 没有 dist 的问题，master 已经有的，dev 昨天脚本跑的有问题，刚刚补上了。npm 上的是正常的
