### ISSUE TITLE
Select组件貌似默认高亮选中和选中颜色有问题

### ISSUE THREAD

**Issue by ShingLi** [youzan/zanui-weapp#332]
按照官网的那样发现 checkedValue  和 activeColor 参数 无效  搜了一下issues 没怎么看懂

**Comment by rex-zsd** [comment]
可以贴下使用的代码吗？看下传入的items和checkedValue。怀疑是使用姿势的问题。

**Comment by ShingLi** [comment]
<zan-select
            items="{{ items }}"
            checkedValue="{{ checkedValue }}"
            activeColor="{{ activeColor }}"
            bind:change="handleSelectChange"
        />
data: {
        duration: 2000,
        $zanui: {
            toptips: {
                show: false
            }
        },
        items: [
            {
                padding: 2,
                value: '1',
                name: '选项一',
            },
            {
                padding:2,
                value: '2',
                name: '选项二',
            }
        ],
        checkedValue: '选项二',
        activeColor: '#ff4443'
    }

{
    "usingComponents": {
        "zan-toptips": "../../lib/dist/toptips/index" ,
        "zan-dialog": "../../lib/dist/dialog/index",
        "zan-select": "../../lib/dist/select/index"
    }
}

**Comment by rex-zsd** [comment]
checkedValue对应的应该是items里面的value呢。
文档里的示例代码有点问题…………
