### ISSUE TITLE
Layout 布局下使用 字体zan-ellipsis--l2样式无效 单行可以

### ISSUE THREAD

**Issue by best-fan** [youzan/zanui-weapp#338]
单行
    `<zan-col` col="24" col-class="zan-ellipsis">
      <image class="detail-end-img" src='http://vote.51what.cn/public/Vote/images/Index/detail_0.png'></image>
      涛哥、鬼鬼、后知、涛哥、鬼鬼、后知、涛哥、鬼鬼、后知、涛哥、鬼鬼、后知、涛哥、鬼鬼、后知、涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 `涛哥、鬼鬼、后知</zan-col>`
![image](https://user-images.githubusercontent.com/18264568/42201317-e301c438-7ec9-11e8-9b27-307633bc7584.png)
多行
    `<zan-col` col="24" col-class=" zan-ellipsis--l2">
      <image class="detail-end-img" src='http://vote.51what.cn/public/Vote/images/Index/detail_0.png'></image>
      涛哥、鬼鬼、后知、涛哥、鬼鬼、后知、涛哥、鬼鬼、后知、涛哥、鬼鬼、后知、涛哥、鬼鬼、后知、涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 涛哥、鬼鬼、后知 `涛哥、鬼鬼、后知</zan-col>`
![image](https://user-images.githubusercontent.com/18264568/42201354-178dbb44-7eca-11e8-8718-cd48aac703c2.png)

**Comment by pangxie1991** [comment]
新版本上已经修复
