### ISSUE TITLE
组件内部元素样式无法覆盖

### ISSUE THREAD

**Issue by HUA616436641** [youzan/zanui-weapp#342]
### 组件内部元素样式无法覆盖。
比如cell组件，默认的externalClasses只有一个cell-class，在组件的标签上加这个属性修改样式可以生效，想修改组件里的zan-cell__bd这个class的样式，是不是只能在externalClasses上加其他class，假如加了zan-cell__bd这个class，组件原有的样式又会丢失，麻烦帮忙解决一下，有没有不改源代码的解决方法
![image](https://user-images.githubusercontent.com/17864476/42357267-ab43420a-8109-11e8-9dc3-4e56f536df8e.png)

**Comment by rex-zsd** [comment]
跟 #243 重复了，可以关注一下那边，这个issue先关闭了。

**Comment by HUA616436641** [comment]
那边几个issue都看过了，但感觉一个 externalClasses: ['cell-class'] 还是解决不了问题啊，其他的子元素样式得怎么改呢

**Comment by laravuel** [comment]
@HUA616436641 是啊，完全没用，哎，捉急

**Comment by laravuel** [comment]
其实官方还不如把组件内的样式都定义到一个样式文件里边，什么都完事了
