### ISSUE TITLE
button能增加form-type

### ISSUE THREAD

**Issue by bfkkkd** [youzan/zanui-weapp#356]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
其实这里开放了 form-type 也是没用的。
微信对于 form 和 button 不在同一层自定义组件或者都直接在页面里的情况，是不允许触发 form-type 相关的功能。咨询了微信，是为了防止刷 form-id。

所以这里就没有添加 form-type 了
