### ISSUE TITLE
执行npm install，提示有漏洞

### ISSUE THREAD

**Issue by Coderkobe** [youzan/zanui-weapp#364]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

![image](https://user-images.githubusercontent.com/18484020/42722652-4d3fc92e-8782-11e8-9ea5-a4db46c4c665.png)

**Comment by pangxie1991** [comment]
我这里新建了一个目录，装了下 zanui-weapp 的依赖，没有任何报错

我看你是直接执行 npm install , 会不会是其他包影响了
或者尝试下切换 npm node 版本试试？
