### ISSUE TITLE
希望能添加更丰富的组件，和Vant-ui的组件保持一致，感谢团队

### ISSUE THREAD

**Issue by kbgyf** [youzan/zanui-weapp#365]
###希望能添加更丰富的组件，和Vant-ui的组件保持一致。

**新增功能
![_20180714194720](https://user-images.githubusercontent.com/37326126/42724102-d0af2680-879e-11e8-8f60-fa1120a9acb1.png)

**Comment by pangxie1991** [comment]
现在主要精力会丰富一些基础的 UI 组件，类似这些业务组件暂时没有计划添加~
