### ISSUE TITLE
文档页面 icon 图片重复

### ISSUE THREAD

**Issue by linrz** [youzan/zanui-weapp#368]
这六行 icon 和下面六行的重复了，有空换张图优化一下~
https://youzan.github.io/zanui-weapp/#/zanui/base/icon
![image](https://user-images.githubusercontent.com/33575974/42742611-a3d99068-88ee-11e8-86f2-1d697bb8a44b.png)

**Comment by rex-zsd** [comment]
好的 感谢反馈
