### ISSUE TITLE
引用zanui的小程序页面报错，最近才有，Expect FLOW_CREATE_NODE but get another

### ISSUE THREAD

**Issue by pengxinlei** [youzan/zanui-weapp#371]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by rex-zsd** [comment]
可以提供下代码片段嘛？

**Comment by pengxinlei** [comment]
似乎没做代码修改，突然就好了
