### ISSUE TITLE
关于新增一个field加btn模板ui的建议

### ISSUE THREAD

**Issue by joyoes** [youzan/zanui-weapp#374]
### 请认真写 ISSUE 的标题，会用于生成 change log。
就是左边是<label>手机号：</label>
中间是:<input>
右边是<button>发送验证码</button>

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by rex-zsd** [comment]
可以自行拼装，`field` 组件暂时不考虑支持右侧按钮。
