### ISSUE TITLE
form里设置zan-button 无法触发submit事件

### ISSUE THREAD

**Issue by vangogogo** [youzan/zanui-weapp#398]
` <form name='lucyForm' report-submit="true" bindsubmit='lucky'>
        <zan-button wx:if="{{status == 1}}" form-type="submit" type="danger" data-taskid="{{id}}">submit</zan-button>
    </form>
`

**Comment by wenlinguo** [comment]
一样遇到

之前看了 iview weapp 好像也有这个问题

**Comment by rex-zsd** [comment]
@vangogogo 目前小程序只有form内直接使用button组件才可以触发submit事件，自定义组件内嵌套button是触发不了的。
所以使用微信的自定义组件开发的UI库都会有这个问题，待微信解决。
目前如果需要触发form的submit事件只能自己手写button。

**Comment by vangogogo** [comment]
@rex-zsd 收到，谢谢
