### ISSUE TITLE
希望支持mpvue

### ISSUE THREAD

**Issue by wanganxp** [youzan/zanui-weapp#400]
目前的文件都是wxml等格式，而mpvue是vue文件，无法直接使用，希望改造支持mpvue。

**Comment by vangogogo** [comment]
好好看看官网，会有惊喜

**Comment by rex-zsd** [comment]
@wanganxp 
zanui-weapp是使用微信官方的自定义组件开发的。
可以去mpvue那里看看他们是否支持微信官方的自定义组件哈。

**Comment by wanganxp** [comment]
官网是：https://www.youzanyun.com/zanui？未发现任何惊喜。
mpvue是vue文件，不支持wxml、wxss的写法。

**Comment by rex-zsd** [comment]
所以你可以去mpvue那提个issue，让他们支持微信官方的自定义组件。
