### ISSUE TITLE
你们的ui组件的单位为什么是px，而不是rpx，如果是px那么对于所有机型的适配是不是存在问题？？？？？

### ISSUE THREAD

**Issue by cc504156085** [youzan/zanui-weapp#402]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by rex-zsd** [comment]
布局的方法有很多，如果使用rpx会有限制。
如果一定要使用rpx可以使用[postcss-px2units](https://www.npmjs.com/package/postcss-px2units)或者[postcss-pxtorpx](https://www.npmjs.com/package/postcss-pxtorpx)把px转成rpx。
