### ISSUE TITLE
CAPSULE 胶囊 样式有点别扭呀，文字有点歪。

### ISSUE THREAD

**Issue by bigzs** [youzan/zanui-weapp#41]
文字都有点靠下了
![tim 20171030102953](https://user-images.githubusercontent.com/25221782/32152157-4c1f5d88-bd5d-11e7-980f-605467f49b80.png)

**Comment by pangxie1991** [comment]
你这个是在电脑上预览的么？
小程序在电脑上的样式和在真机上会有细微的差别，我们以手机预览为准~
