### ISSUE TITLE
我想知道clone话。大概有多大的内容呢？

### ISSUE THREAD

**Issue by mengxuande** [youzan/zanui-weapp#44]
我们知道小程序限制2M的的大小。SO。。。。。如果UI太大的话，也没太大的意义了!

所以，我的问题是：
是需要用什么就丢什么进文件夹然后引什么呢？
还是必须要全部丢进去文件夹。需要的时候引呢？
谢谢，期待回答！~

**Comment by pangxie1991** [comment]
在不使用工具的情况下，
小程序不支持 node_modules，如果通过 bower 安装，只有 `dist` 目录会被安装下来，未压缩大概 200K
因为组件只是提供了基础常用的 UI 组件，所以完全可以通过 bower 安装组件库，一次全部引入

当然，如果考虑更好的优化的话
可以只 `拷贝` 你需要的组件到你的项目目录。
当然，拷贝是一件比较无语的事，用工具解决才是王道~ 
所以我们这段时间会自己做一个工具，根据小程序语法分析依赖，构建更小的代码包。
