### ISSUE TITLE
*新增功能*加一个九宫格的功能。

### ISSUE THREAD

**Issue by aPathFinder** [youzan/zanui-weapp#54]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
九宫格？只是单纯布局的话可以试试 layout
