### ISSUE TITLE
希望有一个api文档的官网或者是规范的文档

### ISSUE THREAD

**Issue by ChazLun** [youzan/zanui-weapp#57]

**Comment by pangxie1991** [comment]
在 packages 目录里，每个组件下都会加 README.md ，这段时间写了几个，今天晚些时候先把这些在最外面的 README.md 上放出来

**Comment by ChazLun** [comment]
好的，谢谢

**Comment by pangxie1991** [comment]
这两天就会放出网页版的 readme，样式还在优化中~

**Comment by pangxie1991** [comment]
已经可以直接访问 [https://www.youzanyun.com/zanui/weapp](https://www.youzanyun.com/zanui/weapp)
