### ISSUE TITLE
组件field怎么清空输入框呢？

### ISSUE THREAD

**Issue by aPathFinder** [youzan/zanui-weapp#59]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
如果在 input 事件中的话，返回空字符串即可
如果需要直接清除文本的话，已在 #60 中支持
