### ISSUE TITLE
Field 输入框

### ISSUE THREAD

**Issue by joe1224** [youzan/zanui-weapp#61]
![87 gz61jwq 04 mls 3lf](https://user-images.githubusercontent.com/22219566/32979402-80979800-cc8f-11e7-9a61-bfffc102eeba.png)
请问不能用吗？

**Comment by pangxie1991** [comment]
你用的是 example 里面的预览吧
拉取最新代码后，在根目录里面执行 `npm run dev` 才可以正常预览

如果还有这个样子的话，麻烦给一个能复现的仓库什么的吧，或者看看 console 有什么报错，这样方便排查。

现在的样子：
![](https://img.yzcdn.cn/public_files/2017/11/18/1861d2d6c73d1cfe160a1f90e11263ca.jpeg)
