### ISSUE TITLE
Popup代码执行的结果和和 "赞组件库演示"小程序两个不一样

### ISSUE THREAD

**Issue by gaoyong06** [youzan/zanui-weapp#74]
### Popup代码执行的结果和和 "赞组件库演示"小程序两个不一样。

**提交bug* **
这是将github上面的代码down下来执行的结果
![0cdf728a-dd8f-4d5c-be1e-25163dce1ee2](https://user-images.githubusercontent.com/1861256/33757973-5d3da7e8-dc37-11e7-89c0-187a0abafa71.png)

这是"赞组件库演示"小程序执行的结果
![img_4335](https://user-images.githubusercontent.com/1861256/33758020-88c89fd0-dc37-11e7-972c-cef29b4e730d.PNG)

代码没更新的样子？？

**Comment by WOWHans** [comment]
同上，用了最新的版本出现了这bug

**Comment by WOWHans** [comment]
@gaoyong06 其实在popup的readme所在的文件夹里有一个.pcss文件里面有相应的css样式，把那部分代码拷到/dist/popub/index.wxss里，然后再改下相应的background-color 就能用了 ~~~~(>_<)~~~~

**Comment by pangxie1991** [comment]
之前是因为还没发版，dist 代码还没同步到最新
建议直接使用 tag 来定位使用的版本~

刚刚发了 2.4.0，现在已经同步了

**Comment by pangxie1991** [comment]
保留 dist 目录提交，是为了方便 bower 工具的使用

**Comment by gaoyong06** [comment]
可以了，感谢上面几位同学。
