### ISSUE TITLE
一像素边框

### ISSUE THREAD

**Issue by shoung6** [youzan/zanui-weapp#80]
后续考虑加入一像素边框兼容嘛？我自己在项目里改写了panel样式用官方button组件的写法实现了一像素边框，目前没有什么问题。

**Comment by shoung6** [comment]
说错了，是cell组件

**Comment by pangxie1991** [comment]
cell，button 组件现在用的就是 1rpx 来实现超细边框的

**Comment by shoung6** [comment]
用rpx没办法实现一像素吧，1rpx在retina屏上是超过1个物理像素的吧

**Comment by pangxie1991** [comment]
这个确实，1rpx 在小屏上可能看不到，大屏上又不够细。。
之后我换成另外的实现吧

**Comment by pangxie1991** [comment]
#87
