### ISSUE TITLE
整体字号偏小，而且各页面字号大小不一

### ISSUE THREAD

**Issue by baiyuxiong** [youzan/zanui-weapp#82]
整体字号偏小，对眼花的老年人不太友好；
而且各页面字号大小不一，看起来有点儿乱。
希望能优化一下

**Comment by pangxie1991** [comment]
这个组件库是根据 ZanUI 来实现的，如果需要面向老年人为主的群体开发小程序的话，可以对部分字体大小重写

另：各页面字号大小不一的，那个是一个演示组件库用的小程序。不同组件使用场景不同，会有不同字号的展示，一般场景都会使用 14px 字体展示

**Comment by Lynn-cc** [comment]
> 这个组件库是根据 ZanUI 来实现的，如果需要面向老年人为主的群体开发小程序的话，可以对部分字体大小重写
> 
> 另：各页面字号大小不一的，那个是一个演示组件库用的小程序。不同组件使用场景不同，会有不同字号的展示，一般场景都会使用 14px 字体展示

请问如何把整体字号都改大一点呢？vars里面不够，难道一个一个组件的字号改么？
