### ISSUE TITLE
在wapy的微信小程序开发的框架里怎么使用这个组件

### ISSUE THREAD

**Issue by wenshan** [youzan/zanui-weapp#84]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by pangxie1991** [comment]
需要在 template 里面引入对应的模板，然后使用
部分组件需要在 js 里面 method 里面扩展对应的方法
