### ISSUE TITLE
tab标签

### ISSUE THREAD

**Issue by 80Arrow** [youzan/zanui-weapp#85]
1.01.1712070没有显示tab标签！
![_20171221151529](https://user-images.githubusercontent.com/7716081/34244743-cf441ea6-e661-11e7-9d09-c767cf608e83.png)

**Comment by pangxie1991** [comment]
这个是在跑项目演示？
项目演示需要在根目录下运行 npm run dev, 然后在 微信开发者工具 里面打开 example 目录

**Comment by Enivel** [comment]
tab 确实挂了

**Comment by pangxie1991** [comment]
@Enivel 能说下具体是怎么挂了的么？
方便的话，帮忙给下具体传入 tab 组件的数据和使用方式吧，还有使用的基础库版本

我这里开了 npm run dev 以后，微信开发者工具 里打开 example 目录是正常的

**Comment by Enivel** [comment]
@pangxie1991  run dev后正常, 我不记得最开始有没有run dev但是其他组件都是正常的唯独 tab.
另外我在自己的项目里引用tab 方法和demo一致也是无法显示.需要做什么操作么?
多谢

**Comment by Enivel** [comment]
@pangxie1991 我在自己的项目中 对zanui 进行npm install + npm run dev 后完整复制官方例子 tab依然为空白

**Comment by pangxie1991** [comment]
@Enivel 你现在在业务里使用最新版本 2.4.2 的试试看

**Comment by Enivel** [comment]
@pangxie1991  可以了 
![image](https://user-images.githubusercontent.com/1982819/34333238-82c7e0b4-e975-11e7-9b60-cffa790ddbfa.png)
