### ISSUE TITLE
tab 点击切换，当前选中的没有高亮

### ISSUE THREAD

**Issue by torlinpeng** [youzan/zanui-weapp#91]
![image](https://user-images.githubusercontent.com/26118575/34399632-146bcfda-ebc4-11e7-8c54-4d08d45c9794.png)
点击不会高亮

**Comment by pangxie1991** [comment]
方便展示下当时的传参么？还有传入数据具体的值

**Comment by torlinpeng** [comment]
<view>
    <template is="zan-tab" data="{{ list, selectedId: '', componentId: 'tab1' }}"></template>
  </view>




![image](https://user-images.githubusercontent.com/26118575/34476222-c666ddc0-efc9-11e7-805e-ae67d1a16965.png)

**Comment by torlinpeng** [comment]
<view>
    <template is="zan-tab" data="{{ list, selectedId: '', componentId: 'tab1' }}"></template>
  </view>

**Comment by pangxie1991** [comment]
tab 的高亮显示是完全根据 selectedId 来的，是不是在模板中传入的 selectedId 没有赋值？
