### ISSUE TITLE
找不到 _handelZanStepperPlus

### ISSUE THREAD

**Issue by x19990416** [youzan/zanui-weapp#95]
按照例子里面的我添加了 Stepper 计数器，但是报 找不到 _handelZanStepperPlus 方法 

Page(Object.assign({}, Zan.Stepper, {
  data: {
    showDialog:false,
    stepper: {
      stepper: 10,
      min: 1,
      max: 20
    },
  },

  handleZanStepperChange(e) {
    // 如果页面有多个Stepper组件，则通过唯一componentId进行索引
    var compoenntId = e.componentId;
    var stepper = e.stepper;
    console.log(compoenntId)
    console.log(stepper)
    this.setData({
      'stepper.stepper': stepper
    });
  },

**Comment by pangxie1991** [comment]
Zan 这个是从 require('path/to/zanui-weapp/dist/index') 引入的么？
可以把 Zan.Stepper 打印出来下，看看是不是引用错了
